{% set version = "0.3.8" %}

package:
  name: vale-ls
  version: {{ version }}

source:
  url: https://github.com/errata-ai/vale-ls/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c739fef40348f22f6fda29772a2a3ad8a6fcb7321a9b22bbf33303007677b39e

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - pkg-config              # [linux]
    - make                    # [linux]
    - cargo-bundle-licenses
  host:
    - bzip2    # [not win]
    - openssl  # [not win]
    - zstd     # [not win]
  run:
    - vale >=3.0.0

test:
  requires:
    - m2-grep  # [win]
  commands:
    - vale-ls --version
    - vale-ls --help
    - vale-ls --version | grep -iE "{{ version.replace(".", "\.") }}"

about:
  home: https://vale.sh
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: An implementation of the Language Server Protocol (LSP) for the Vale command-line tool.
  dev_url: https://github.com/errata-ai/vale-ls
  doc_url: https://vale.sh/docs/integrations/guide

extra:
  recipe-maintainers:
    - bollwyvl
