{% set version = "0.5.0" %}

package:
  name: vale-ls
  version: {{ version }}

source:
  url: https://github.com/errata-ai/vale-ls/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2ff774132bb022f12416e7bc12c37bd76e0e6b06473bd14fef40a0063fde6514

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - pkg-config              # [linux]
    - make                    # [linux]
    - cargo-bundle-licenses
  host:
    - bzip2    # [not win]
    - openssl  # [not win]
    - zstd     # [not win]
  run:
    - vale >=3.0.0

test:
  requires:
    - m2-grep  # [win]
  commands:
    - vale-ls --version
    - vale-ls --help
    - vale-ls --version | grep -iE {{ version.replace(".", "\.") }}

about:
  home: https://vale.sh
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: An implementation of the Language Server Protocol (LSP) for the Vale command-line tool.
  dev_url: https://github.com/errata-ai/vale-ls
  doc_url: https://vale.sh/docs/integrations/guide

extra:
  recipe-maintainers:
    - bollwyvl
