# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.6.0"
  grep: ${{ 'grep -iE ' if unix else 'findstr /r /c:' }}

package:
  name: vale-ls
  version: ${{ version }}

source:
  url: https://github.com/errata-ai/vale-ls/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 0645f643ba6d1c5b5d641a100a0d7135661fada60a630f38032812959806f4e5

build:
  number: 0
  script:
    env:
      OPENSSL_DIR: ${{ "$PREFIX" if unix else "%LIBRARY_PREFIX%" }}
      CARGO_PROFILE_RELEASE_LTO: fat
      CARGO_PROFILE_RELEASE_STRIP: symbols
      ZSTD_SYS_USE_PKG_CONFIG: "1"
      LZMA_API_STATIC: "0"
      BZIP2_NO_PKG_CONFIG: "0"
    content:
      - cargo auditable install -v --no-track --locked --root="${{ PREFIX }}" --profile=release --path=.
      - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
      - if: win
        then:
          - md "%SCRIPTS%" || echo "%SCRIPTS% already exists"
          - move "%PREFIX%\bin\vale-ls.exe" "%SCRIPTS%"

requirements:
  build:
    - ${{ compiler("rust") }}
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
    - cargo-auditable
    - make
    - pkg-config
  host:
    - bzip2
    - zstd
  run:
    - vale >=3.0.0

tests:
  - package_contents:
      strict: true
      bin:
        - vale-ls
  - script:
      - vale-ls --version
      - vale-ls --help
      - vale-ls --version | ${{ grep }}${{ version | replace(".", "\.") }}

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: An implementation of the Language Server Protocol (LSP) for the Vale command-line tool.
  homepage: https://vale.sh
  repository: https://github.com/errata-ai/vale-ls
  documentation: https://vale.sh/docs/integrations/guide

extra:
  recipe-maintainers:
    - bollwyvl
